services:
  lab:
    image: lab
    volumes:
      - $ENTRY/container_local:/home/ubuntu/.local
      - $ENTRY/data/nvim-props:/home/ubuntu/nvim-props
      - $ENTRY/config/nvim:/home/ubuntu/.config/nvim
